### ISSUE TITLE
Implement simple spin-loop service for uptime-checker

### ISSUE THREAD

**Issue by evanpurkhiser** [getsentry/uptime-checker#2]
```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/uptime-checker/pull/8
- [ ] https://github.com/getsentry/uptime-checker/pull/9
- [ ] https://github.com/getsentry/uptime-checker/pull/15
```
