### ISSUE TITLE
Configured docker + cloudbuild for uptime-checker

### ISSUE THREAD

**Issue by evanpurkhiser** [getsentry/uptime-checker#3]
```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/uptime-checker/pull/16
- [ ] https://github.com/getsentry/uptime-checker/pull/17
- [ ] https://github.com/getsentry/ops/pull/10772
- [ ] https://github.com/getsentry/ops/pull/10779
```
