### ISSUE TITLE
Configure gocd pipelines for cloud checker

### ISSUE THREAD

**Issue by evanpurkhiser** [getsentry/uptime-checker#4]
```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/uptime-checker/pull/20
- [ ] https://github.com/getsentry/security-as-code/pull/806
- [ ] https://github.com/getsentry/ops/pull/10823
```

**Comment by evanpurkhiser** [comment]
W're going to need #18 first

**Comment by evanpurkhiser** [comment]
This is waiting on the operations team to fix the service account needed for us to deploy to GKE
