### ISSUE TITLE
Create kafka topic in kafka-small for receiving check configurations

### ISSUE THREAD

**Issue by evanpurkhiser** [getsentry/uptime-checker#6]
Part of the work here is going to be defining what the kafka topic schema looks like. Probably something like this https://www.notion.so/sentry/Uptime-Technical-Design-28220c8d876842259fe274e3544162fb?pvs=4#90bad75e9eff40ceaabd9aa6fd8d44cf

We'll want to implement this in https://github.com/getsentry/sentry-kafka-schemas
```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry-kafka-schemas/pull/313
- [ ] https://github.com/getsentry/ops/pull/11283
- [ ] https://github.com/getsentry/ops/pull/11289
```
